name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install
        uses: pnpm/action-setup@v6
        with:
          cache: true
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
